Add proper logging for stealing-type cards
terraforming-mars/terraforming-mars pull request #3803
Opened 2021-11-23 18:29 UTC by erisalke

Issue: https://github.com/terraforming-mars/terraforming-mars/issues/3175

<img width="710" alt="Screenshot 2021-11-23 at 18 51 00" src="https://user-images.githubusercontent.com/15717649/143081277-bf445756-35df-4194-824d-843ebf35a0dc.png">
<img width="712" alt="Screenshot 2021-11-23 at 18 57 53" src="https://user-images.githubusercontent.com/15717649/143081288-1f11d1f4-3cbb-40e5-bc60-4b5a1ebdca84.png">

2021-11-25 01:54 UTC, kberg requested changes
Thanks for thinking about this! Let me know if you want me to knock out generalizing DecreaseProduction etc.

2021-11-25 01:54 UTC, kberg commented on src/Player.ts
> +      isStealing?: boolean
I think shorten this to `stealing`

2021-11-25 01:54 UTC, kberg commented on src/Player.ts
> +    isStealing = false
short here to `stealing` too.

2021-11-25 01:54 UTC, kberg commented on src/Player.ts
> +      b.player(from)
While I agree that your grammar is better than what logUnitDelta has, I expect the name order will bew confusing as players scan the log. This could be made simpler by just reusing logUnitDelta.

Change 
```
if (from !== undefined) {
  message = message + ' by ' + ((from instanceof Player) ? '${4}' : 'Global Event');
}
```

to

```
if (from !== undefined) {
  if (stealing === true) {
    message = message + ' stolen';
  }
  message = message + ' by ' + ((from instanceof Player) ? '${4}' : 'Global Event');
}
```

2021-11-25 01:54 UTC, kberg commented on src/Player.ts
> +    options? : { log: boolean, from? : Player | GlobalEventName, isStealing?: boolean}
Shorten `isStealing` here, too.

2021-11-25 01:54 UTC, kberg commented on src/cards/base/AsteroidMiningConsortium.ts
> +    const decreaseAction = new DecreaseAnyProduction(player, Resources.TITANIUM, 1);
So if this were me I'd move much of the parameters to an object, just like `GainResources` The object would contain count (default to 1), title (defaulted to its current value) and stealing (default to false.) That'll be much simpler.

However, I'd probably do that in a completely separate PR or commit. If you like I'll do that.

2021-11-26 14:54 UTC, erisalke commented on src/Player.ts
> +      b.player(from)
Keep the same message format, sure thing.

2021-11-26 15:06 UTC, erisalke commented on src/cards/base/AsteroidMiningConsortium.ts
> +    const decreaseAction = new DecreaseAnyProduction(player, Resources.TITANIUM, 1);
I extracted the `Options` as follows:
```
export interface Options {
  count: number,
  stealing?: boolean
}
```
Therefore, all the previous calls changed 
from: `player.game.defer(new DecreaseAnyProduction(player, Resources.TITANIUM, 1));`
to: `player.game.defer(new DecreaseAnyProduction(player, Resources.TITANIUM, {count: 1}));`
and the stealing calls look this way:
`player.game.defer(new DecreaseAnyProduction(player, Resources.TITANIUM, {count: 1, stealing: true}));`

One thing I did't include into the `Options` was the title. For the moment all the existing calls use the default value - so it makes more sense to remove the parameter completely instead and hide it inside the class itself. And composing the "options" where the title is optional, but have a default value, and such value depends on the "count" which as well has a default value and may be optional... it's just messy.
I believe it's "good enough" for now. Maybe in future PRs if you really believe it's necessary.

2021-11-26 17:40 UTC, kberg reviewed
This is a good change. Normally I'd want to see some tests, but we kind of avoid many of the logging tests. If you can manually reverify these, this will be good enough with no more changes. (Or if you want to write a unit test, I won't mind! :D)

Once this is verified, I'll merge it in. Thank you!

Thanks!

2021-11-26 17:40 UTC, kberg commented on src/cards/base/EnergyTapping.ts
> +      new DecreaseAnyProduction(player, Resources.ENERGY, {count:1, stealing:true}));
So one thing about reformatting on the fly is that it makes reviews more complicated.

![image](https://user-images.githubusercontent.com/413481/143614757-9cdb4ff3-1045-43f0-a4ca-bd1e1da4bb85.png)

Now I have to read the whole thing, whereas if you had just kept it on one line I could just the latter half of the line.

Don't make any changes, because I'll have read all of them by the time you get this.

2021-11-26 17:40 UTC, kberg commented on src/cards/base/AsteroidMiningConsortium.ts
> +      {count: 1, stealing: true}
Is this "stealing"? It looks like it, but is it?

2021-11-26 17:40 UTC, kberg commented on src/deferredActions/DecreaseAnyProduction.ts
> +    public title: string = 'Select player to decrease ' + resource + ' production by ' + options.count + ' step(s)',
I agree with your assessment of title. I think I'd still put it in options, as options tends to be the last parameter. But don't bother, this is great.

2021-11-26 17:40 UTC, kberg commented on src/deferredActions/DecreaseAnyProduction.ts
> +        found.addProduction(this.resource, -this.options.count, { log: true, from: this.player, stealing: this.options.stealing });
There's no `decreaseProduction` method, is there? That's fine.

2021-11-26 17:40 UTC, kberg commented on src/cards/base/PowerSupplyConsortium.ts
> +      new DecreaseAnyProduction(player, Resources.ENERGY, {count:1, stealing:true}));
Should there be a StealProduction deferred action? Not in this PR, just thinking.

2021-11-26 17:42 UTC, kberg commented on src/cards/base/AsteroidMiningConsortium.ts
> +    const decreaseAction = new DecreaseAnyProduction(player, Resources.TITANIUM, 1);
As you said, I also believe this is "good enough." You saw some of my comments lamenting that the API that existed before you came in here could have been better, but those can be dealt with another time. Thank you for this!

2021-11-29 17:29 UTC, erisalke commented on src/cards/base/AsteroidMiningConsortium.ts
> +      {count: 1, stealing: true}
Depends how you define "stealing" I believe if one player lost "X" and other player gains exactly the same "X" (in this case titanium production) it is best described as "stealing" :D

2021-11-29 17:32 UTC, erisalke commented on src/deferredActions/DecreaseAnyProduction.ts
> +        found.addProduction(this.resource, -this.options.count, { log: true, from: this.player, stealing: this.options.stealing });
nope, there's only the `addProduction` used with negative values

2021-11-30 03:12 UTC, kberg commented
> This is a good change. Normally I'd want to see some tests, but we kind of avoid many of the logging tests. If you can manually reverify these, this will be good enough with no more changes. (Or if you want to write a unit test, I won't mind! :D)
> 
> Once this is verified, I'll merge it in. Thank you!
> 
> Thanks!

Thanks for the responses, etc. Just a reminder that my request above remains. Thanks again!

2021-11-30 10:19 UTC, erisalke commented
@kberg All the changes were tested and works fine. You can see the results in the screens attached on the top. I think we could merge it now.

2021-11-30 16:21 UTC, kberg commented
Those at the top are from before you made changes to the code, so it needs
another verification.

On Tue, Nov 30, 2021, 5:19 AM piotrek ***@***.***> wrote:

> @kberg <https://github.com/kberg> All the changes were tested and works
> fine. You can see the results in the screens attached on the top. I think
> we could merge it now.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/terraforming-mars/terraforming-mars/pull/3803#issuecomment-982492669>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AADE6KL2YY2NQUNVO53QQATUOSQLVANCNFSM5IUF77GQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-12-03 12:11 UTC, erisalke commented
@kberg ah no, sorry for not being clear enough 😓 
When I said: "All the changes were tested and works fine", I meant that I've **just finished** re-testing this.
In other words, it was checked that all works fine AFTER the last commit was made. It's javascript, we take no risks :)

2021-12-03 16:05 UTC, kberg approved these changes

2021-12-03 16:05 UTC, kberg commented
AHA! Thank you. This looks good. Thank you!

On Fri, Dec 3, 2021 at 7:11 AM piotrek ***@***.***> wrote:

> @kberg <https://github.com/kberg> ah no, sorry for not being clear enough
> 😓
> When I said: "All the changes were tested and works fine", I meant that
> I've *just finished* re-testing this.
> In other words, it was checked that all works fine AFTER the last commit
> was made. It's javascript, we take no risks :)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/terraforming-mars/terraforming-mars/pull/3803#issuecomment-985469427>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AADE6KPLR2OIVUP5QOYM7G3UPCXYDANCNFSM5IUF77GQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-12-03 16:18 UTC, merged