Use type guard for action cards.
terraforming-mars/terraforming-mars pull request #3896
Opened 2021-12-24 20:45 UTC by kberg

2021-12-29 18:14 UTC, bafolts requested changes
I would change `isIActionCard` to the following:

```
export function isIActionCard(card: ICard | IActionCard): card is IActionCard {
  return card.action !== undefined && card.canAct !== undefined;                                   
} 
```

This will ensure what we are passed is what we expect and not `any`. It also couples the check with `IActionCard`. If for example we were to have a typo and use `card.actio` instead of `card.action` typescript covers us.

```
src/cards/ICard.ts:31:15 - error TS2551: Property 'actio' does not exist on type 'IActionCard | ICard'. Did you mean 'action'?
  Property 'actio' does not exist on type 'IActionCard'.
  ```

2021-12-29 18:19 UTC, kberg commented
> I would change `isIActionCard` to the following:
> 
> ```
> export function isIActionCard(card: ICard | IActionCard): card is IActionCard {
>   return card.action !== undefined && card.canAct !== undefined;                                   
> } 
> ```
> 
> This will ensure what we are passed is what we expect and not `any`. It also couples the check with `IActionCard`. If for example we were to have a typo and use `card.actio` instead of `card.action` typescript covers us.
> 
> ```
> src/cards/ICard.ts:31:15 - error TS2551: Property 'actio' does not exist on type 'IActionCard | ICard'. Did you mean 'action'?
>   Property 'actio' does not exist on type 'IActionCard'.
> ```

Will do in a couple of hours. Right now I just want to ask: why do so many stackoverflow posts recommend the style I presented?

2021-12-29 19:38 UTC, kberg commented
> Will do in a couple of hours. Right now I just want to ask: why do so many stackoverflow posts recommend the style I presented?

Ignore my question.

2021-12-30 00:58 UTC, bafolts approved these changes

2021-12-30 02:01 UTC, merged