Centralize greenery counting, will simplify Wetlands.
terraforming-mars/terraforming-mars pull request #3976
Opened 2022-01-22 22:13 UTC by kberg

Depends on #3975

2022-01-23 22:20 UTC, bafolts commented on src/cards/base/EcologicalZone.ts
> +      .filter((space) => player.game.board.getAdjacentSpaces(space).filter(Board.isGreenerySpace).length > 0);
We could change this later but since this is checking for `length > 0` we should be able to swap with `.some(Board.isGreenerySpace)`.

2022-01-23 22:23 UTC, bafolts commented on src/cards/base/ImmigrationShuttles.ts
> +    return Math.floor(player.game.getCitiesCount(player) / 3);
Should this be `getCitiesCount`? The victory point is rewarded for any city tile in play.

2022-01-23 22:31 UTC, bafolts commented on src/turmoil/parties/Greens.ts
> +    const count = boardSpaces.filter((space) => Board.isGreenerySpace(space) && space.player !== undefined && space.player.id === player.id).length;
I think this can be `Board.isGreenerySpace(space) && Board.isOwnedBy(player)`

2022-01-23 22:34 UTC, bafolts requested changes
Pretty sure I spotted a typo in ImmigrationShuttles. Otherwise only had minor suggestions.

2022-01-24 05:04 UTC, kberg commented on src/cards/base/ImmigrationShuttles.ts
> +    return Math.floor(player.game.getCitiesCount(player) / 3);
Good catch.

2022-01-24 05:05 UTC, kberg commented on src/cards/base/ImmigrationShuttles.ts
> +    return Math.floor(player.game.getCitiesCount(player) / 3);
Added additional test to ImmigrationShuttles.

2022-01-24 05:07 UTC, kberg commented on src/turmoil/parties/Greens.ts
> +    const count = boardSpaces.filter((space) => Board.isGreenerySpace(space) && space.player !== undefined && space.player.id === player.id).length;
It's not that neat: it's

`Board.ownedBy(player)(space)` beause ownedBy returns a function.

2022-01-24 05:08 UTC, kberg commented on src/turmoil/parties/Greens.ts
> +    const count = boardSpaces.filter((space) => Board.isGreenerySpace(space) && space.player !== undefined && space.player.id === player.id).length;
Rolling it back, it's not pretty.

2022-01-24 23:22 UTC, bafolts approved these changes

2022-01-24 23:59 UTC, merged