provide clone game id without list
terraforming-mars/terraforming-mars pull request #4072
Opened 2022-02-10 23:54 UTC by bafolts

I still want to add unit tests for the server side stuff here but I tested this through browser and it seems to work.

This changes the dropdown for selecting a cloneable game to an input box. The value provided is then verified before we call to create the game. Right now about 1 MB is downloaded querying for the list of cloneable games. The dropdown is nearly impossible to navigate to find a game id. Bandwidth will be decreased. Games will be cloned.

2022-02-12 03:08 UTC, kberg reviewed
This is good stuff.

2022-02-12 03:08 UTC, kberg commented on src/client/components/create/CreateGameForm.vue
> +          alert(this.$t('Game id ' + component.clonedGameId + ' not found'));
Is it possible to be consistent about naming? Predefined game, cloneable game, game. Follow-up is possible, though let's get the service path right.

2022-02-12 03:08 UTC, kberg commented on src/database/IDatabase.ts
> +     * Load reference to game that can be cloned. Every game is cloneable,
Every _completed_ game is cloneable.

2022-02-12 03:08 UTC, kberg commented on src/database/IDatabase.ts
> +     * exist.
s/it won't exist/this won't return it.

2022-02-12 03:08 UTC, kberg commented on src/database/LocalFilesystem.ts
> +    this.getGames((err, gameIds) => {
This can be simpler. Probably close to

```
try {
  const text = fs.readFileSync(this._historyFilename(gameId, 0));
  const serializedGame = JSON.parse(text) as SerializedGame;
  cb(...)
} catch(err) {
  cb(err, ...); or something.
}
```

2022-02-12 03:08 UTC, kberg commented on tests/database/SQLite.spec.ts
> +  it('gets cloneable game by id', async () => {
Could you add a test where the game doesn't exist?

2022-02-12 03:08 UTC, kberg commented on tests/utils/setup.ts
>    getClonableGames: () => {},
Is this line still necessary?

2022-02-12 11:25 UTC, bafolts commented on src/routes/ApiCloneableGames.ts
> +        console.warn('Could not load cloneable game: ', err);
If the ID doesn't exist an `undefined` will be returned. The error would happen if there were some other database error.

2022-02-12 11:27 UTC, bafolts commented on src/client/components/create/CreateGameForm.vue
> +      const serializedData = await this.serializeSettings();
The `async/await` is added here for the introduced call to `fetch`. The `await fetch` requires an `async` up the call stack.

2022-02-12 11:29 UTC, bafolts commented on tests/utils/setup.ts
>    getClonableGames: () => {},
The `getClonableGames` function hasn't been removed from `IDatabase` so this is still necessary.

2022-02-12 15:19 UTC, kberg commented on src/routes/ApiCloneableGames.ts
> +        console.warn('Could not load cloneable game: ', err);
> If the ID doesn't exist an `undefined` will be returned. The error would happen if there were some other database error.

:+1:

2022-02-12 15:20 UTC, kberg commented
I added some naming comments; the only one I kinda care about is the path naming. The others can happen later (I'm happy to do them.) Besides that this PR is good to go.

2022-02-15 23:41 UTC, bafolts commented
> I added some naming comments; the only one I kinda care about is the path naming. The others can happen later (I'm happy to do them.) Besides that this PR is good to go.

What should we name the path?

2022-02-16 03:32 UTC, kberg commented
> > I added some naming comments; the only one I kinda care about is the path naming. The others can happen later (I'm happy to do them.) Besides that this PR is good to go.
> 
> What should we name the path?

Hmm. How about `cloneablegame`? or `cloneable`?

2022-02-18 23:53 UTC, bafolts commented
This has the build failure on windows error most likely due to node 16 but I made the naming change to `cloneablegame` for the route.

2022-02-19 00:23 UTC, kberg approved these changes

2022-02-19 00:23 UTC, kberg commented
Thanks! This is a good change.

2022-02-19 16:34 UTC, kberg commented on .github/workflows/main.yml
> +        node-version: '14.x'
Can you roll back this file? I've dropped windows from 2022 to 2019, and that does the trick.

2022-02-19 16:34 UTC, kberg requested changes
Will go back to approve after main.yml is resolved.

2022-02-21 15:34 UTC, bafolts commented
@kberg I reverted the main.yml change and builds passed thanks to #4130

2022-02-21 16:01 UTC, kberg approved these changes

2022-02-21 16:01 UTC, merged