Add Korean translations
terraforming-mars/terraforming-mars pull request #4305
Opened 2022-04-14 05:19 UTC by derornos

- UI, main menu, ...
- corperation cards: base, prel, venus, colony, turmoil, promo
- not yet: prel cards, project cards, fan-made cards

2022-04-14 12:12 UTC, kberg commented
Wow! Thank you.

2022-04-14 12:12 UTC, alrusdi commented
Great work!

2022-04-14 12:13 UTC, kberg commented on src/client/components/card/CardCorporationLogo.vue
> +      <span class="card-unmi-logo">ＵNITED<br/>ＮATIONS<br/>ＭARS<br/>ＩNITIATIVE</span>
What is this change? (It's also completely unrelated to Korean translations.)

2022-04-14 12:17 UTC, kberg commented on src/locales/ko/promo_corporations.json
> +  "C": "이",
Does this work? How intersting.

2022-04-14 12:22 UTC, kberg commented on src/locales/ko/start_screen.json
> +    "Not affiliated with FryxGames, Asmodee Digital or Steam in any way.": "FryxGames, Asmodee Digital 및 Steam과 제휴하지 않았습니다. / 옮긴이: 푸른이(derornos)"
I'd be happy to credit you, let's put it on README.md. What do you think?

2022-04-14 14:17 UTC, derornos commented on src/locales/ko/promo_corporations.json
> +  "C": "이",
![pil](https://user-images.githubusercontent.com/15874357/163409463-b5e50838-d78f-4658-a2d3-e298d0750b58.PNG)
![spl](https://user-images.githubusercontent.com/15874357/163409468-1ed4e39b-e607-42fd-a78a-6e179cb01078.PNG)

I wanted to make sure that part of the text was applied in a different design as well. For example, by changing the color of only one special letter.

2022-04-14 14:19 UTC, derornos commented on src/locales/ko/start_screen.json
> +    "Not affiliated with FryxGames, Asmodee Digital or Steam in any way.": "FryxGames, Asmodee Digital 및 Steam과 제휴하지 않았습니다. / 옮긴이: 푸른이(derornos)"
Of course I agree. But people who want to play the game can easily ignore it if it's not translated. I was concerned about it.

2022-04-14 14:22 UTC, derornos commented
There are no translated materials for other fan-made extensions, but there are translated materials for the 'pathfinder' extension in Korea. However, it is a pity that there is no json file to refer to.

Please let me know what should I do.

ps. I apologize to all of you for my poor English, which is dependent on Google Translator.

2022-04-14 14:38 UTC, alrusdi commented on src/client/components/card/CardCorporationLogo.vue
> +      <span class="card-unmi-logo">ＵNITED<br/>ＮATIONS<br/>ＭARS<br/>ＩNITIATIVE</span>
Other translations use original (english) corporations names. Is it uncommon for korean to use original brand names if they contain latin letters? I mean something like Mars, McDonalds, Apple etc.

2022-04-14 14:39 UTC, alrusdi commented on src/locales/ko/promo_corporations.json
> +  "C": "이",
it is brilliant by the way :-)

2022-04-14 23:50 UTC, derornos commented on src/client/components/card/CardCorporationLogo.vue
> +      <span class="card-unmi-logo">ＵNITED<br/>ＮATIONS<br/>ＭARS<br/>ＩNITIATIVE</span>
Like McDonalds and 맥도날드, Apple and 애플, in Korea, both the korean pronunciation and the original English are used.

When I translate the MARS of UNMI, MARS on the main screen was translated the same. (Part of the letters 'Terraforming Mars') I needed to change the original letters because I wanted to be expressed at the beginning of each line of one letter of UNMI.

2022-04-15 16:26 UTC, alrusdi approved these changes

2022-04-15 17:54 UTC, kberg commented on src/client/components/card/CardCorporationLogo.vue
> +      <span class="card-unmi-logo">ＵNITED<br/>ＮATIONS<br/>ＭARS<br/>ＩNITIATIVE</span>
So there's one problem - this invalidates all the other translations. I'm going to ask that for this one, although the style is terrific, that you use the same mechanism as the other translations.

In other words, undo the change to `CardCorporationLogo` and use a single line for the logo.

That way, it's simple and it works. And, later, we can discuss a better solution.

Is that OK?

2022-04-15 17:55 UTC, kberg commented on src/locales/ko/promo_corporations.json
> +  "C": "이",
I agree. I worry that might impact other places where we might have a "C". But that's a bigger problem. Don't worry.

2022-04-15 17:56 UTC, kberg commented on src/locales/ko/start_screen.json
> +    "Not affiliated with FryxGames, Asmodee Digital or Steam in any way.": "FryxGames, Asmodee Digital 및 Steam과 제휴하지 않았습니다. / 옮긴이: 푸른이(derornos)"
The translation is great.

What I'm asking is:
1. Remove your name from start_screen.json
2. Add an entry to README.md.

Is that OK?

2022-04-15 17:56 UTC, kberg reviewed
This is really good.

2022-04-16 02:02 UTC, derornos commented on src/client/components/card/CardCorporationLogo.vue
> +      <span class="card-unmi-logo">ＵNITED<br/>ＮATIONS<br/>ＭARS<br/>ＩNITIATIVE</span>
okay : )

2022-04-16 02:05 UTC, derornos commented on src/locales/ko/start_screen.json
> +    "Not affiliated with FryxGames, Asmodee Digital or Steam in any way.": "FryxGames, Asmodee Digital 및 Steam과 제휴하지 않았습니다. / 옮긴이: 푸른이(derornos)"
okay!

2022-04-16 04:17 UTC, kberg commented on src/locales/ko/start_screen.json
> +    "Not affiliated with FryxGames, Asmodee Digital or Steam in any way.": "FryxGames, Asmodee Digital 및 Steam과 제휴하지 않았습니다. / 옮긴이: 푸른이(derornos)"
OK. Let me know when they are done.

2022-04-18 15:20 UTC, kberg commented
@derornos just in case you didn't understand, I am waiting for you to make those two changes.

2022-04-19 01:00 UTC, kberg commented on src/client/components/card/CardCorporationLogo.vue
> +      <span class="card-unmi-logo">ＵNITED<br/>ＮATIONS<br/>ＭARS<br/>ＩNITIATIVE</span>
Thanks for changing the start screen. Restore UNMI and everything should be good to go.

2022-04-19 01:07 UTC, kberg requested changes
Once UNMI is fixed, this should be good to co.

2022-04-19 06:31 UTC, derornos commented on src/client/components/card/CardCorporationLogo.vue
> +      <span class="card-unmi-logo">ＵNITED<br/>ＮATIONS<br/>ＭARS<br/>ＩNITIATIVE</span>
![001](https://user-images.githubusercontent.com/15874357/163939817-8c34a5b9-5c14-498d-9d8e-d503b8d2ff3a.PNG)
![002](https://user-images.githubusercontent.com/15874357/163939830-806f7761-a997-4f96-b04a-14478af2bc2f.PNG)

The 'MARS' character of UNMI becomes the translated value of the 'MARS' character on the first screen.

2022-04-19 06:38 UTC, derornos commented on src/client/components/card/CardCorporationLogo.vue
> +      <span class="card-unmi-logo">ＵNITED<br/>ＮATIONS<br/>ＭARS<br/>ＩNITIATIVE</span>
However, the line-by-line translation I want does not apply at all, and even if I translate the whole, the logo is not applied.
I want to apply the translation for that logo too. I wonder if there is a good way.
What should I do?

![003](https://user-images.githubusercontent.com/15874357/163941118-b4310f4c-d572-4967-b5ec-2230b604eb9e.PNG)
![004](https://user-images.githubusercontent.com/15874357/163941158-f39452bc-13e1-4dad-a76f-49371ff4b629.PNG)

2022-04-19 06:47 UTC, kberg commented on src/client/components/card/CardCorporationLogo.vue
> +      <span class="card-unmi-logo">ＵNITED<br/>ＮATIONS<br/>ＭARS<br/>ＩNITIATIVE</span>
To start with, I'd like to not change the text for UNMI at all. I realize that might mean that some of the translations aren't perfect, but it means we can get all the rest of your hard work out and available.

Once that's done we can look at UNMI more closely.

It's 3AM here. Goodnight! :D

2022-04-19 16:45 UTC, kberg commented on src/locales/ko/start_screen.json
> +    "__TERRAFORMING__": "테　라　포　밍",
Does __TERRAFORMING__ work?

2022-04-19 23:04 UTC, derornos commented on src/locales/ko/start_screen.json
> +    "__TERRAFORMING__": "테　라　포　밍",
No. it is just comment for future improvement.

because when it is translated, there is a problem that only the MARS part of UNMI is translated.

2022-04-20 04:15 UTC, kberg approved these changes
Looks great. Thank you!

2022-04-20 04:26 UTC, merged

2022-05-01 19:02 UTC, kberg commented on src/locales/ko/moon_cards.json
> +  "Ancient Shipyards (Nerfed)": "",
Hi -- where did you get this text from? This is not on any of our cards.

2022-05-02 06:29 UTC, derornos commented on src/locales/ko/moon_cards.json
> +  "Ancient Shipyards (Nerfed)": "",
https://github.com/terraforming-mars/terraforming-mars/blob/main/src/locales/cn/moon_cards.json

: )