Configure removing finished games from the running server.
terraforming-mars/terraforming-mars pull request #4685
Opened 2022-07-14 02:55 UTC by kberg

2022-07-15 22:44 UTC, bafolts requested changes
This looks good and should allow the terraforming-mars.herokuapp.com server to go more than 24 hours without running out of memory 🥳 

I have a few minor comments. Requesting changes mostly for the `setTimeout` that doesn't have a corresponding `clearTimeout`. Manual users could eventually have multiple sweepers running which I don't think is intentional.

2022-07-15 22:44 UTC, bafolts commented on .env.sample
> +##  basis to find and evict compmleted games. When 'manual' the server doesn't
```suggestion
##  basis to find and evict completed games. When 'manual' the server doesn't
```

2022-07-15 22:44 UTC, bafolts commented on src/database/GameIds.ts
> +    game.getPlayers().forEach((p) => (p as any)._game = undefined);
```suggestion
    game.getPlayers().forEach((p) => p.game = undefined);
```

This will involve updating the setter for `game` to take `Game | undefined` as well. Will avoid using `any` and we allow `game` to be `undefined` on `Player`.

2022-07-15 22:44 UTC, bafolts commented on src/database/GameIds.ts
> +function scheduleSweep(cache: GameIds, sleepMillis: number) {
If this is called manually we may need to call to `clearTimeout`. I would store the timeout from `setTimeout` and when this function is called then clear it. This will ensure subsequent calls to `scheduleSweep` don't start multiple sweepers.

2022-07-15 22:44 UTC, bafolts commented on src/database/GameLoader.ts
> +  public resetForTesting(): void {
Other places we have leveraged a class within the unit test that extends the class to have methods for testing only. Here `idsContainer` could be made `protected` and the unit test class could override `reset`.

2022-07-15 22:44 UTC, bafolts commented on src/database/GameLoader.ts
> +function parseConfigString(stringValue: string): CacheConfig {
Is the format of this configuration string a standard for duration? Taking in seconds would avoid having this string parsing and could be more straight forward. Instead of passing in 15m users could pass in 900.

2022-07-16 18:54 UTC, kberg commented on src/database/GameIds.ts
> +    game.getPlayers().forEach((p) => (p as any)._game = undefined);
Yeah, sorry. I fixed it. PTAL. Making game take undefined will be a huge maintenance issue. A proper fix is to define Game before Player, and not the other way around.

There's another possibility which relies on `GameLoader.getGame` but that's slower and messier. A proper refactor seems the right step forward.

2022-07-16 18:54 UTC, kberg commented on src/database/GameIds.ts
> +    game.getPlayers().forEach((p) => (p as any)._game = undefined);
The solution I will push shortly seems the right compromise.

2022-07-16 18:56 UTC, kberg commented on src/database/GameIds.ts
> +function scheduleSweep(cache: GameIds, sleepMillis: number) {
It's not exported, so it won't be called unnecessarily. Is this still an issue?

2022-07-16 18:59 UTC, kberg commented on src/database/GameLoader.ts
> +  public resetForTesting(): void {
Hi -- first, this is the `reset` method from above moved down and given a new name for clarity. This is a fine idea, but can be its own isolated change.

2022-07-16 18:59 UTC, kberg commented on src/database/GameLoader.ts
> +function parseConfigString(stringValue: string): CacheConfig {
You can pass '15m' or '900s' or '10m300s' or '.25h'.

2022-07-16 20:16 UTC, bafolts commented on src/Player.ts
> +    this.game = undefined as unknown as Game;
Before I recommended the change I updated the `set game` to take `Game | undefined` as it's argument and I didn't run into compilation issues throughout the app. The type of `_game` is already `Game | undefined`.

2022-07-16 20:21 UTC, bafolts commented on src/database/GameLoader.ts
> +function parseConfigString(stringValue: string): CacheConfig {
This looks close to https://en.wikipedia.org/wiki/ISO_8601#Durations. Was asking as I was curious if there was some other duration standard.

2022-07-16 20:22 UTC, kberg commented on src/Player.ts
> +    this.game = undefined as unknown as Game;
Yes, that's right. I removed the setter and getter.

2022-07-16 20:23 UTC, kberg commented on src/Player.ts
> +    this.game = undefined as unknown as Game;
Yes, that's right. I removed the setter and getter.

2022-07-16 20:24 UTC, kberg commented on src/database/GameLoader.ts
> +function parseConfigString(stringValue: string): CacheConfig {
It is close to that! There's no duration API until a later standard. And it also includes some irritating prefixes that I was hoping to avoid.

2022-07-16 20:24 UTC, kberg commented on src/database/GameLoader.ts
> +function parseConfigString(stringValue: string): CacheConfig {
It is close to that! There's no duration API until a later standard. And it also includes some irritating prefixes that I was hoping to avoid.

2022-07-16 20:25 UTC, bafolts approved these changes

2022-07-16 20:33 UTC, merged