Update log_messages.json
terraforming-mars/terraforming-mars pull request #5106
Opened 2022-10-28 09:52 UTC by Borbarad2

Even more improvements for the log messages, oriented by korean translation

2022-11-02 05:01 UTC, kberg requested changes

2022-11-02 05:01 UTC, kberg commented on src/locales/de/log_messages.json
> +    "heat": "Wärme"
I think you forgot a comma on this line.

2022-11-02 08:55 UTC, Borbarad2 commented on src/locales/de/log_messages.json
> +    "heat": "Wärme"
Yes, a comma is missing in this line.

2022-11-04 05:58 UTC, kberg approved these changes

2022-11-04 05:58 UTC, merged