Translation fix
terraforming-mars/terraforming-mars pull request #5125
Opened 2022-11-14 12:43 UTC by nicobubulle

Another translation fix.

2022-11-14 17:18 UTC, kberg commented
Lint is complaining: https://github.com/terraforming-mars/terraforming-mars/actions/runs/3461566578/jobs/5779337004#step:5:66

2022-11-15 05:20 UTC, kberg commented on src/client/components/Awards.vue
> +        <a @click.prevent="toggleList" class="ma-clickable awards-padding" href="#" data-test="toggle-awards" v-i18n>Awards</a>
This isn't actually a change, is it?

2022-11-15 05:22 UTC, kberg requested changes

2022-11-15 05:22 UTC, kberg commented on src/client/components/colonies/Colony.vue
> +      <span v-if="colony.name === ColonyName.PLUTO" class="colony-background-color" style="position:relative; top:-3px"
I appreciate the reformatting, but it makes reading the meaningful differences tricky. If all you did is add v-i18n in these places, can you just keep it as it was?

2022-11-15 10:21 UTC, nicobubulle commented on src/client/components/colonies/Colony.vue
> +      <span v-if="colony.name === ColonyName.PLUTO" class="colony-background-color" style="position:relative; top:-3px"
I noticed that if the string is not inside the tag, the translation is not parsed :
v-i18n>
Trade Income
</span>
Don't work but
v-i18n>Trade Income</span>
works

2022-11-15 10:22 UTC, nicobubulle commented on src/client/components/Awards.vue
> +        <a @click.prevent="toggleList" class="ma-clickable awards-padding" href="#" data-test="toggle-awards" v-i18n>Awards</a>
same issue here

2022-11-15 13:59 UTC, kberg approved these changes

2022-11-15 14:00 UTC, merged