CEO#4.6 - DeferredAction PlaceHazardTile
terraforming-mars/terraforming-mars pull request #5293
Opened 2023-02-06 09:42 UTC by d-little

### [src/server/deferredActions/PlaceHazardTile.ts](https://github.com/terraforming-mars/terraforming-mars/compare/main...d-little:ceoPlaceHazardTile?expand=1#diff-e243312c29bfacbd52cc95772f1bf0f3c85eade8c2cad715c2d5a5a3a1ca95f8)

Hopefully fairly obvious.  Currently nothing uses this, but Caesar will.  After that there are a handful of Community Cards that interact with Hazards in Ares.

2023-02-07 00:59 UTC, kberg requested changes

2023-02-07 00:59 UTC, kberg commented on src/server/Game.ts
> +  public addHazardTile(
This isn't really how a hazard tile gets placed. See `_AresHazardPlacement.putHazardAt`. Perhaps this is obvious to me, and not to someone else. But a hazard isn't _really_ treated like a tile in the traditional sense.

Anyway, use that method, even though _AresHazardPlacement is meant to be "package private". I'll deal with that later.

2023-02-07 00:59 UTC, kberg commented on src/server/Game.ts
> +  public addHazardTile(
In fact, remove this method, and call .putHazardAt in PlaceHazardTile.

2023-02-07 00:59 UTC, kberg commented on src/server/deferredActions/PlaceHazardTile.ts
> +      hazardType?: TileType,
Typescript fun! Change `TileType` to `TileType.DUST_STORM_MILD | TileType.EROSION_MILD`

2023-02-07 00:59 UTC, kberg commented on src/server/Game.ts
> +  public addHazardTile(
By the way, this has the additional effect of giving someone placement bonuses for a hazard, which should not apply. (FYI @nwai90 in case you want to consider that for the Community server.)

2023-02-07 00:59 UTC, kberg commented on src/server/deferredActions/PlaceHazardTile.ts
> +    const hazardType = this.options?.hazardType || Math.floor(Math.random() * 2) === 0 ? TileType.DUST_STORM_MILD : TileType.EROSION_MILD;
This is a little janky. First, I think the card doesn't say it's a randomly-selected hazard type. Second, why would that matter? It only matters somewhat thematically, but I think it's worth considering. The different global parameters conditions for Ares makes a) certain hazard types technically unavailable b) certain hazard types severe or c) intentionally removed.

The simplest thing, I think, is to merely say that the card places a mild erosion. That way it doesn't get removed when the temperature goes above a certain amount, and can still be upgraded to severe. This is a thematic problem I've had with  placing a hazard tile for some time.

2023-02-07 00:59 UTC, kberg commented on src/server/deferredActions/PlaceHazardTile.ts
> +    const type = this.options?.on || 'land';
No. Hazard spaces are only playable on available land spaces. It should be reasonable to remove this.options.on.

2023-02-07 13:52 UTC, d-little commented on src/server/deferredActions/PlaceHazardTile.ts
> +    const hazardType = this.options?.hazardType || Math.floor(Math.random() * 2) === 0 ? TileType.DUST_STORM_MILD : TileType.EROSION_MILD;
Makes sense.  I've made the hazardType mandatory, but I imagine _most_ cards will place mild erosion.  I'll need to eyeball the other community cards (if we add them) to see if they should add anything other than this.

2023-02-08 03:29 UTC, kberg approved these changes

2023-02-08 03:30 UTC, merged