Optimize the intersection check
terraforming-mars/terraforming-mars pull request #5329
Opened 2023-02-09 21:56 UTC by aloisdg

Hi!

This is a minor modification to optimize a very narrow part of the code. It does not matters much but here it goes :)

Thanks a lot for your work

2023-02-10 03:04 UTC, kberg requested changes
Minor change. Thank you!

2023-02-10 03:04 UTC, kberg commented on tests/ma/MilestoneAwardSelector.spec.ts
> +/**
This would be better off in utils, for the same reason that hasIntersection is better in utils  instead of Counter.

2023-02-10 03:08 UTC, kberg commented
Also, this looks like it isn't going to build:

```

> terraforming-mars@1.0.0 build:server
> tsc --build src/tsconfig.json

src/common/utils/utils.ts(27,3): error TS2322: Type 'boolean' is not assignable to type 'T[]'.
The command '/bin/sh -c npm run build' returned a non-zero code: 1
Error: Process completed with exit code 1.
```

Please make sure to run `npm install`, `npm run build` and `npm run test`, and then `npm run lint`. Thanks!

2023-02-10 08:54 UTC, aloisdg commented on tests/ma/MilestoneAwardSelector.spec.ts
> +/**
Not sure how the code is deployed, but I guessed (and I a may be wrong), that the tests folder where not a part of the deploy-able. Since `intersection` is not needed in the client nor the server, is there a specific reason to move it under `src`?

2023-02-10 10:12 UTC, aloisdg commented
I didn't try the code jet. I will do it later on.

2023-02-10 13:52 UTC, kberg commented on tests/ma/MilestoneAwardSelector.spec.ts
> +/**
I wasn't thinking about tests/utils, but I'd really rather it be back where it was. The additional cost on the client-side download isn't going to be meaningful. (Having just cut the download size in half.)

Utility methods in the `tests` package are typically for the testing API only.

Leave it where you put it, but I will move it back there. The speed optimization is very welcome, though!

2023-02-10 15:22 UTC, aloisdg commented
Error come from the linter. I will have to clone the code after all... :)

2023-02-10 21:49 UTC, aloisdg commented on tests/ma/MilestoneAwardSelector.spec.ts
> +/**
I am ok with that. Done.

2023-02-10 22:16 UTC, kberg approved these changes

2023-02-10 22:16 UTC, kberg commented
Thank you for this!

2023-02-10 22:25 UTC, merged

2023-02-11 02:14 UTC, aloisdg commented
You are welcome! Thank your for the help!