CEO - Init Faraday
terraforming-mars/terraforming-mars pull request #5346
Opened 2023-02-12 04:27 UTC by d-little

### Faraday

A lot of strange moving parts, hopefully they're put together well

2023-02-12 05:38 UTC, kberg reviewed
This looks pretty good!

2023-02-12 05:38 UTC, kberg commented on src/server/cards/ceos/Faraday.ts
> +      new SelectOption(`Pay 2 M€ to draw a ${tag} card`, 'Confirm', () => {
I wonder if we can make this easier to internationalize, though I don't know how much it'll matter.

2023-02-12 05:38 UTC, kberg commented on src/server/cards/ceos/Faraday.ts
> +        player.drawCard(1, {tag: tag});
use `SelectPaymentDeferred.options.afterPay` to draw the card only once the ability is paid for.

2023-02-12 05:38 UTC, kberg commented on src/server/cards/ceos/Faraday.ts
> +  private getAllValidTags(player: Player): Array<Tag> {
Use `player.tags.getAllTags()`

2023-02-12 06:35 UTC, kberg commented on tests/cards/ceo/Faraday.spec.ts
> +    const orOpations = cast(game.deferredActions.pop()!.execute(), OrOptions);
orOpations

2023-02-12 06:35 UTC, kberg commented on tests/cards/ceo/Faraday.spec.ts
> +    expect(game.deferredActions).has.lengthOf(0);
What I do instead of counting deferred actions this way is calling

```
runAllActions();
expect(player.getWaitingFor()).is.undefined;
```

This has a strange side effect of dealing with how games are initialized. (It requires some special behavior which I won't describe tonight because I'm tired. If you just do what I wrote above, you'll hit the problem I'm describing, so in many ways, this is just fine.

2023-02-12 06:35 UTC, kberg commented on tests/cards/ceo/Faraday.spec.ts
> +    const orOptions = cast(game.deferredActions.pop()!.execute(), OrOptions);
Same here. Instead of counting deferred actions.

```
runAllActions();
const orOptions = cast(player.popWaitingFor(), OrOptions);
```

2023-02-13 06:22 UTC, d-little commented on tests/cards/ceo/Faraday.spec.ts
> +    expect(game.deferredActions).has.lengthOf(0);
I've copyed the way `HabitatMarte.spec.ts` works, put `player.popWaitingFor()` into `beforeEach`

2023-02-13 06:52 UTC, d-little commented on src/server/cards/ceos/Faraday.ts
> +  private getAllValidTags(player: Player): Array<Tag> {
I avoided this at first, and I cannot remember why... I added it in but it might be more complicated than I needed to make it, but I'm not sure how efficient find is vs. associative arrays in TS!

2023-02-14 01:26 UTC, kberg commented on src/server/cards/ceos/Faraday.ts
> +  private getAllValidTags(player: Player): Array<Tag> {
Given that this is only called when events are played when someone has Faraday, this is OK. As I've said I'm still kind of desperate to measure some of the areas of poor performance.

2023-02-14 01:26 UTC, kberg commented on src/server/cards/ceos/Faraday.ts
> +  private getAllValidTags(player: Player): Array<Tag> {
By this, I mean "getAllTags"

2023-02-14 01:29 UTC, kberg requested changes
OK, let me know when this is updated. Thanks!

2023-02-14 01:29 UTC, kberg commented on src/server/cards/ceos/Faraday.ts
> +      // Modulo 5 what the tag count was before the card was played.
If a player meets the requirement for two tag types due to a single card play, they a) aren't told it, and b) not given an option for the order they are resolved.

2023-02-14 03:07 UTC, d-little commented on src/server/cards/ceos/Faraday.ts
> +      // Modulo 5 what the tag count was before the card was played.
Would this look something like:

```ts
return new OrOptions(
  if tagsToDraw.length > 0 {
    for (tag in tagsToDraw){ 
      new SelectOption('Pay 2MC to draw card with ${tag} tag', 'Draw card', () => { 
        // pay 2mc
        // draw card
        // return to this loop
      }),
     }
     new SelectOption('Do nothing', 'Confirm', () => {
       // exit the whole loop
     }
  }
);
```

2023-02-15 02:59 UTC, kberg commented on src/server/cards/ceos/Faraday.ts
> +      // Modulo 5 what the tag count was before the card was played.
I had something else in mind, but let's revisit this.

2023-02-15 04:40 UTC, d-little commented on src/server/cards/ceos/Faraday.ts
> +        player.drawCard(1, {tag: tag});
Done, I think :)

2023-02-15 04:41 UTC, d-little commented
Shall I wait on the Tags work before finalising this?

2023-02-15 04:56 UTC, kberg approved these changes

2023-02-15 04:57 UTC, merged