CEO Gaia
terraforming-mars/terraforming-mars pull request #5462
Opened 2023-03-09 01:14 UTC by d-little

### Gaia

I'm almost certain I've not implemented this correctly. The original had a lot of custom work, I figured I could just use the Ares' own `earnAdjacencyBonuses`... I hope I was right

![image](https://user-images.githubusercontent.com/2050250/223889570-9b06634c-ae36-4a18-baeb-e488201ead81.png)

2023-03-14 06:53 UTC, kberg reviewed
Seems pretty reasonable. A couple of minor changes?

2023-03-14 06:53 UTC, kberg commented on src/server/cards/ceos/Gaia.ts
> +      space.tile?.tileType !== undefined && space.spaceType !== SpaceType.COLONY,
I'm not positive, but I suspect it would do well to add `space.player !== undefined` and `!isHazardType(space.tile)`. What do you think?

2023-03-14 06:53 UTC, kberg commented on src/server/cards/ceos/Gaia.ts
> +        AresHandler.earnAdjacencyBonuses(aresData, player, space);
This might improperly count the Ares Networker milestone. Consider adding an optional parameter to `earnAdjacencyBonuses` that doesn't track the Networker.

2023-03-16 21:38 UTC, d-little commented on src/server/cards/ceos/Gaia.ts
> +      space.tile?.tileType !== undefined && space.spaceType !== SpaceType.COLONY,
Wouldnt `space.player !== undefined` remove the bonuses from Ocean tiles?

Hazard tiles is curious.  Gaia does say _all_ tiles... I'm not sure what the design decision there would be. @nwai90 ?

2023-03-21 05:19 UTC, kberg commented on src/server/cards/ceos/Gaia.ts
> +        AresHandler.earnAdjacencyBonuses(aresData, player, space);
ping!

2023-04-01 02:20 UTC, kberg approved these changes

2023-04-01 02:20 UTC, kberg commented on src/server/ares/AresHandler.ts
> +  public static earnAdjacencyBonuses(aresData: AresData, player: Player, space: ISpace, isTileBeingPlaced = true) {
This is fine, but I think the better option is to split out the milestone stuff into its own function. I can do that post-merge.

2023-04-01 02:20 UTC, kberg commented on src/server/cards/ceos/Gaia.ts
> +      space.tile?.tileType !== undefined && space.spaceType !== SpaceType.COLONY,
Wow, Oceans. OK? /shrug

2023-04-01 02:20 UTC, kberg commented
Nice work.

2023-04-01 02:25 UTC, kberg commented on src/server/cards/ceos/Gaia.ts
> +      space.tile?.tileType !== undefined && space.spaceType !== SpaceType.COLONY,
From @nwai90:
![image](https://user-images.githubusercontent.com/413481/229261499-92354f33-217f-41e6-b445-e3be722c8a2e.png)

2023-04-01 02:27 UTC, kberg requested changes
(this is a vestigial comment to change the review state back to 'request changes')

2023-04-05 00:44 UTC, d-little commented on src/server/cards/ceos/Gaia.ts
> +      space.tile?.tileType !== undefined && space.spaceType !== SpaceType.COLONY,
I'd have to go back to the Ares rules, but do Ocean tiles not grant adjacency bonuses on placement?  I was pretty sure they did

2023-04-05 03:27 UTC, kberg commented on src/server/cards/ceos/Gaia.ts
> +      space.tile?.tileType !== undefined && space.spaceType !== SpaceType.COLONY,
They do, but apparently according to @nwai90 they don't apply. /shrug?

2023-04-05 03:36 UTC, nwai90 commented on src/server/cards/ceos/Gaia.ts
> +      space.tile?.tileType !== undefined && space.spaceType !== SpaceType.COLONY,
Ocean tiles do grant adjacency bonuses on initial placement. The reason they were excluded initially is for balance reasons. The effect is potentially a lot stronger if oceans were also included, especially because it will apply to adjacencies that would not have been originally granted (i.e. placing an Ares tile where there are already adjacent tiles, suddenly those neighbor tiles will apply for this effect)

2023-04-05 04:37 UTC, d-little commented on src/server/cards/ceos/Gaia.ts
> +      space.tile?.tileType !== undefined && space.spaceType !== SpaceType.COLONY,
> The effect is potentially a lot stronger if oceans were also included, especially because it will apply to adjacencies that would not have been originally granted (i.e. placing an Ares tile where there are already adjacent tiles, suddenly those neighbor tiles will apply for this effect)

That would apply here anyway, right?  How does excluding Oceans change that behaviour?

I'm happy to update with **Once per game, gain the Ares adjacency bonuses of all non-ocean tiles placed on Mars.',**

2023-04-06 03:26 UTC, kberg commented on src/server/cards/ceos/Gaia.ts
> +      space.tile?.tileType !== undefined && space.spaceType !== SpaceType.OCEAN && space.spaceType !== SpaceType.COLONY,
spaceType !== ocean will omit counting Mangrove. You probably want space.tile.tileType.

![image](https://user-images.githubusercontent.com/413481/230264383-45abb6a5-6d92-4b02-b208-d4cbf925afeb.png)

This will also count hazard tiles. Consider

space.tile !== undefined && (space.tile.tileType  !== TileType.OCEAN && !isHazardTile(tile.tileType)) && space.spaceType !== SpaceType.COLONY.

2023-04-06 05:31 UTC, d-little commented on src/server/cards/ceos/Gaia.ts
> +      space.tile?.tileType !== undefined && space.spaceType !== SpaceType.OCEAN && space.spaceType !== SpaceType.COLONY,
It grants Ares tiles too, I think?

@nwai90 Maybe Gaia can be updated to only grant adjacency bonuses to tiles with 'owners', those with marker-cubes on them.  That would remove the Oceans and Ares tiles, but keep all other tiles in play?

2023-04-07 16:22 UTC, kberg approved these changes

2023-04-07 16:22 UTC, merged