Refactoring
terraforming-mars/terraforming-mars pull request #6552
Opened 2024-04-03 06:58 UTC by EthanDobbs

2024-04-03 20:27 UTC, kberg requested changes
It's still hard for me to tell what is going on. There's a series of behavioral refactorings, some semantic ones, and some seem to be stylistic preferences. I can't tell the motivations behind a few of them. Deferred actions, and their ordering, is a pretty critical part of the system so I want to be careful here.

2024-04-03 20:27 UTC, kberg commented on src/server/Game.ts
> +  public defer<T>(action: DeferredAction<T>, priority?: Priority): DeferredAction<T> {
Help me understand why this is better.

2024-04-03 20:27 UTC, kberg commented on src/server/deferredActions/DeferredActionsQueue.ts
> +  public get IsEmpty(): boolean {
Name as `isEmpty` please, and keep it as a function instead of a getter, please.

2024-04-03 20:27 UTC, kberg commented on src/server/deferredActions/DeferredActionsQueue.ts
> +  /** Adds a deferred action to the queue, then sorts the queue. */
No need to describe that it sorts the queue, since that is an implementation detail. The queue delivers messages in order.

2024-04-03 20:27 UTC, kberg commented on src/server/deferredActions/DeferredAction.ts
> +  /** Executed a callback function with a parameter determined by the child class of DeferredAction */
Thanks for adding a description. This description talks about how something is executed. I suggest instead:

> Stores `cb`, to be called after this deferred action completes.

2024-04-03 20:27 UTC, kberg commented on src/server/deferredActions/DeferredActionsQueue.ts
> +  // This function should be moved to the DeferredAction class, so GiveColonyBonus can override the function, instead using of this hook
Prefix with TODO(ethandobbs): please

2024-04-03 20:27 UTC, kberg commented on src/server/deferredActions/DeferredActionsQueue.ts
> +    // GiveColonyBonus hook so that all players can give a response at the same time.
The original comment was just fine, and contained more information.

2024-04-03 20:27 UTC, kberg commented on src/server/deferredActions/DeferredActionsQueue.ts
> +    if (input) {
the original was fine, thanks.

2024-04-03 20:27 UTC, kberg commented on src/server/deferredActions/DeferredActionsQueue.ts
> +  // The following methods are used in tests
I'd rather not add functions just for test unless the behavior is really encapsulated.

2024-04-04 21:03 UTC, EthanDobbs commented on src/server/Game.ts
> +  public defer<T>(action: DeferredAction<T>, priority?: Priority): DeferredAction<T> {
There is no direct benefit, other than I had trouble understanding what was going on and this change made more sense to me. I can understand though why the interface existed tho. If you insisted on re-adding it, I would add comments as to why it exists.

2024-04-04 21:06 UTC, EthanDobbs commented on src/server/deferredActions/DeferredActionsQueue.ts
> +    // GiveColonyBonus hook so that all players can give a response at the same time.
Yeah this change was result of wanting to delete the hook, then deciding that was a job for a later time.

2024-04-04 21:10 UTC, EthanDobbs commented on src/server/deferredActions/DeferredActionsQueue.ts
> +    if (input) {
Yeah, it's an aesthetic preference of mine. I'll opt for 'if (x !== undefined)' instead of 'if (x)' in cases like this where readability is more important than being concise (so, nearly every case).

2024-04-04 23:26 UTC, kberg commented on src/server/Game.ts
> +  public defer<T>(action: DeferredAction<T>, priority?: Priority): DeferredAction<T> {
By providing a more narrow API, it informs callers that its use is to only attach an andThen.

2024-05-08 05:12 UTC, kberg commented
Feel free to reopen this and/or create a new PR when you are ready.

2024-05-08 05:12 UTC, closed without merging