Fix the included cards functionality by only adding them to project c…
terraforming-mars/terraforming-mars pull request #6586
Opened 2024-04-13 01:22 UTC by rvangrinsven

…ards

2024-04-13 01:23 UTC, rvangrinsven commented
@kberg I also noticed the issue you mentioned in another pull request. I think this solves all problems.

2024-04-13 19:41 UTC, kberg commented
Thanks. Let's get a test in there that proves this fixes the problem. Hang out, I'll put something together.

2024-04-13 19:53 UTC, kberg commented
Actually, a little manual testing and it's clear this doesn't quite fix the feature. I can add any kind of card, even a Prelude

![image](https://github.com/terraforming-mars/terraforming-mars/assets/413481/dbe9aa86-ec28-45ef-af95-95d8bbfa8bc8)

![image](https://github.com/terraforming-mars/terraforming-mars/assets/413481/db77ec68-a5c7-4a7f-8301-94b7f5b86317)

The included cards feature should only apply to project cards (since other types of cards have their own exclusion/inclusion mechanism.) Make these two tests pass. (Give them better test names, please.)

```
  it('test name', function() {
    const gameOptions: GameOptions = {
      ...DEFAULT_GAME_OPTIONS,
      corporateEra: true,
      includedCards: [CardName.DONATION],
    };
    expect(() => new GameCards(gameOptions)).to.throw(/Donation is not a project card/);
  });

  it('test name', function() {
    const gameOptions: GameOptions = {
      ...DEFAULT_GAME_OPTIONS,
      corporateEra: true,
      includedCards: [CardName.VENUSIAN_INSECTS],
    };
    const names = new GameCards(gameOptions).getCorporationCards().map((c) => c.name);
    expect(names).to.not.contain(CardName.VENUSIAN_INSECTS);
  });
```

There are no tests for the UI, but if you can look there I would be grateful.

2024-04-13 19:58 UTC, kberg commented
I am disabling the feature from the UI for the time being at https://github.com/terraforming-mars/terraforming-mars/pull/6588. I suspect once the issues I pointed out are fixed, the feature can be re-enabled. I can do that in a separate PR (just by rolling back #6588)

2024-04-16 14:16 UTC, kberg requested changes
Changing the state to "changes requested"

2024-04-17 00:23 UTC, rvangrinsven commented on src/client/components/create/CardsFilter.vue
> -  ...getCards(byType(CardType.PRELUDE)),
I think removing Preludes from both the included cards and excluded cards select box makes sense, since for prelude we have a separate functionality anyway. This has caused unintended behavior for us in the past anyway when combining these.

2024-04-17 00:24 UTC, rvangrinsven commented on tests/GameCards.spec.ts
> +  it('should not include corporation cards in the included cards', function () {
I didn't let it throw an error as in your example, but just filter out all non project cards that people might have manually added in a settings json file.

2024-04-17 00:24 UTC, rvangrinsven commented
@kberg I've adjusted the PR. Only thing still missing is UI tests, if necessary maybe you could give a starting point?

2024-04-17 04:25 UTC, kberg commented
> @kberg I've adjusted the PR. Only thing still missing is UI tests, if necessary maybe you could give a starting point?

Don't do UI tests, it's not fair. I think manual testing there is enough.

2024-04-17 04:25 UTC, kberg reviewed
This is a good change. I will run it again locally, but I think this is good to go.

2024-04-17 04:25 UTC, kberg commented on src/client/components/create/CardsFilter.vue
> -  ...getCards(byType(CardType.PRELUDE)),
Let me think through the impact: it's going to be in the case where someone has a JSON file which uses the "exclude cards" behavior. But I think that may be acceptable. If it causes problems, I'll own it instead of kicking it back to you.

2024-04-17 04:25 UTC, kberg commented on src/server/GameCards.ts
> +        card.type !== CardType.CORPORATION &&
How about  instead be inclusive rather than exclusive? e.g.

```
return card.type === CardType.AUTOMATED || card.type === CardType.ACTIVE || card.type === CardType.EVENT;
```

If a new type, like CEO, comes in, this is the safer approach.

2024-04-17 04:25 UTC, kberg commented on tests/GameCards.spec.ts
> +  it('should not include the included cards in the standard projects', function() {
Ooh more and more tests. Thank you!

2024-04-17 04:25 UTC, kberg commented on tests/GameCards.spec.ts
> +  it('should not include corporation cards in the included cards', function () {
OIK good

2024-04-17 04:26 UTC, kberg commented
> This is a good change. I will run it again locally, but I think this is good to go.

Modulo that minor change I requested on how you filter card types.

2024-04-17 14:43 UTC, kberg approved these changes
Took a few tries, but I fixed that last bit. Good work.

2024-04-17 14:44 UTC, merged