Norwegian localization and various translations fixes
terraforming-mars/terraforming-mars pull request #6599
Opened 2024-04-16 12:30 UTC by JTBringe

2024-04-16 14:15 UTC, kberg requested changes
Thanks for all of this! I typically ask that changes like this are isolated. For instance, there are some changes you make that are not isolated to translations, and could be their own PR. The one that changes the `common` code, for instance, is now a point of debate which delays getting all the rest of it in.

2024-04-16 14:15 UTC, kberg commented on src/client/components/GameEnd.vue
> +import {$t} from '@/client/directives/i18n';
It is not allowed to import `client` code into `common`, sorry.

2024-04-16 14:15 UTC, kberg commented on src/client/components/OtherPlayer.vue
> +      <div class="player_name" v-i18n> {{ player.name }} played cards </div>
This can't really be translated since the player name is not parameterized.

2024-04-16 14:15 UTC, kberg commented on src/client/components/help/HelpIconology.vue
> -            <br>
This is an intentional break. Is there a reason why you removed it?

2024-04-16 14:15 UTC, kberg commented on src/styles/language_hacks.less
> +.language-de {
What is this doing?

2024-04-16 14:15 UTC, kberg commented on src/styles/language_icon.less
> +  position: relative;
What is this doing?

2024-04-17 10:07 UTC, JTBringe commented on src/client/components/help/HelpIconology.vue
> -            <br>
I removed it in the beginning of December, but then I reverted the change a few days later.
For some reason it was removed in the version I pushed now.
Anyhow, I'll fix it.

2024-04-17 10:17 UTC, JTBringe commented on src/styles/language_icon.less
> +  position: relative;
Default is position: static, which prevents z-index from having an effect.

2024-04-17 10:17 UTC, JTBringe commented on src/styles/language_hacks.less
> +.language-de {
It changes "VP" on the player info to "SP", to align with Norwegian and German translations.
When the player changes languages the <body> gets a class that reflects the language, such as language-nb.
I've corrected a mistake with the classname for Norwegian (from -no to -nb), pushing it soon.

2024-04-17 10:18 UTC, JTBringe commented on src/client/components/OtherPlayer.vue
> +      <div class="player_name" v-i18n> {{ player.name }} played cards </div>
You're right. For some reason I thought I saw it working when doing local testing, but it must've been something with a similar wording. I'll remove it.

2024-04-17 10:21 UTC, JTBringe commented on src/client/components/GameEnd.vue
> +import {$t} from '@/client/directives/i18n';
GameEnd.vue is a file in the client folder, and there's several imports from both common and client into that file.

2024-04-17 14:07 UTC, kberg approved these changes
Looks great. It looks like by the commit history that you've been working on this for some time. Thanks once more. :rocket:

2024-04-17 14:07 UTC, kberg commented on src/client/components/GameEnd.vue
> +import {$t} from '@/client/directives/i18n';
I mistakenly _this file_ was in `/common`. My mistake, sorry.

2024-04-17 14:08 UTC, kberg commented
Dangit, merge conflicts: 
![image](https://github.com/terraforming-mars/terraforming-mars/assets/413481/75a6a72c-8b6f-4263-9d7a-0490b53a1b66)

LMK if you're stuck.

2024-04-17 19:51 UTC, merged