Randomisation of Moon tiles
terraforming-mars/terraforming-mars pull request #6635
Opened 2024-04-25 17:02 UTC by ryoku

Implements #6365

Shuffling of Moon tiles is enabled through a specific option in the Game setup screen

2024-04-26 00:19 UTC, kberg requested changes
I'll have to look at the algorithm more closely. So this is an initial pass.

2024-04-26 00:19 UTC, kberg commented on src/server/boards/BoardBuilder.ts
> +  /*
What's the plan here?

2024-04-26 00:19 UTC, kberg commented on src/client/components/create/CreateGameForm.vue
> +                            <template v-if="moonExpansion">
I appreciate the extra effort, but let's just use the shuffle parameter already available. I don't feel that there's a strong reason to have one shuffled but not the other. At least, it's not worth the conceptual and maintenance weight.

2024-04-26 00:19 UTC, kberg commented on tests/boards/BoardBuilder.spec.ts
> +  it('Randomizes map for Moon', () => {
This behavior doesn't have anything to do with BoardBuilder. It probably belongs someplace else.

2024-04-26 07:39 UTC, ryoku commented on src/server/boards/BoardBuilder.ts
> +  /*
No specific plan, I spent time analysing this and in the end I realised it is not used, so I think it could be removed to reduce cognitive load. If you are ok I will remove it rather than commenting. If there is specific reason that I do not see to keep the function I will remove the comments.

2024-04-26 08:07 UTC, ryoku commented on src/client/components/create/CreateGameForm.vue
> +                            <template v-if="moonExpansion">
Actually this was my first implementation. I will revert back to it.

2024-04-26 08:08 UTC, ryoku commented on src/client/components/create/CreateGameForm.vue
> +                            <template v-if="moonExpansion">
You are right! Moved to MoonBoard.spec.ts

2024-04-26 08:08 UTC, ryoku commented on tests/boards/BoardBuilder.spec.ts
> +  it('Randomizes map for Moon', () => {
You are right! Moved to MoonBoard.spec.ts

2024-04-26 08:24 UTC, ryoku commented on src/client/components/create/CreateGameForm.vue
> +                            <template v-if="moonExpansion">
It's done

2024-04-26 10:18 UTC, Borbarad2 commented
@ryoko: Are you available on discord, too? What is your name there?

2024-04-26 14:26 UTC, kberg commented on src/server/boards/BoardBuilder.ts
> +  /*
You know what? Leave it for a bit. The board API needs one more cleanup phase. Thanks for identifying it though!

2024-04-26 14:26 UTC, kberg commented on src/server/moon/MoonBoard.ts
> +    if (gameOptions.shuffleMapOption!== undefined && gameOptions.shuffleMapOption) {
Can be shortened to `if (gameOptions.shuffleMapOption === true)`

2024-04-26 14:26 UTC, kberg commented on tests/moon/MoonBoard.spec.ts
> +  it('sanity', () => {
I added this sanity test which ensures that the default board doesn't actually change based on the rewrite. And that's enough for me to approve the PR (once the tests finish.)

If they don't pass it means something's funny with the new setup code.

2024-04-26 14:33 UTC, kberg approved these changes
Thank you. This is a good change.

2024-04-26 14:34 UTC, kberg commented
Looks like it's blocked now on a merge conflict. :/

2024-04-26 17:08 UTC, ryoku commented
> @Ryoko: Are you available on discord, too? What is your name there?

Yes, here my nick: ryoku5049

2024-04-27 10:55 UTC, kberg approved these changes
Thank you!

2024-04-27 10:55 UTC, kberg commented
Still got merge conflicts. :/

2024-04-27 10:56 UTC, merged

2024-04-27 10:56 UTC, kberg commented
Nope never mind, it's good