5 Prelude Cards
terraforming-mars/terraforming-mars pull request #6807
Opened 2024-07-13 15:03 UTC by maserion

[Prelude 2]: Envoys from Venus
[Prelude 2]: Colonial Representation
[Prelude 2]: Jovian Envoys
[Prelude 2]: Microgravity Nutrition
[Prelude 2]: Soil Studies

2024-07-13 15:49 UTC, kberg commented
![image](https://github.com/user-attachments/assets/95073ad1-80ca-438e-abbe-f38ca6c34426)
![image](https://github.com/user-attachments/assets/fc392c57-c3ed-4c29-a3d9-a876d03d5363)
![image](https://github.com/user-attachments/assets/f2904e50-2ac6-439e-8f13-203ace4dbce0)
![image](https://github.com/user-attachments/assets/faed48c1-7f4b-4d7d-b066-40695af7c7de)
![image](https://github.com/user-attachments/assets/f31e8277-1a6e-40ed-855e-39259a289f23)

@maserion this looks great!

2024-07-13 15:56 UTC, kberg commented
So the lack of a substantial test for Microgravity Nutrition means I definitely can't merge it right now. But we can do that.

2024-07-13 16:50 UTC, kberg commented on src/server/cards/prelude2/MicrogravityNutrition.ts
> +  public override bespokePlay(player: IPlayer) {
I think this can be reduced to

`production: {megacredits: {colonies: {colonies: {}}}},`

2024-07-13 16:50 UTC, kberg commented on src/server/cards/prelude2/SoilStudies.ts
> +      metadata: {
Reduce to 

```
      metadata: {
        cardNumber: 'P81',
        renderData: CardRenderer.builder((b) => {
          b.plants(1).slash().tag(Tag.VENUS).tag(Tag.PLANT).colonies(1).br;
        }),
        description: 'Requires that temperature is -4 C or lower. Gain 1 plant per Venus tag, plant tag, and colony you have.',
      },
```

2024-07-13 16:58 UTC, maserion commented on src/server/cards/prelude2/MicrogravityNutrition.ts
> +  public override bespokePlay(player: IPlayer) {
this part is taken fgrom EcologyResearch.ts
```
  public override bespokePlay(player: IPlayer) {
    const coloniesCount = player.getColoniesCount();
    player.production.add(Resource.PLANTS, coloniesCount, {log: true});
 }
```

2024-07-13 18:35 UTC, kberg commented
Do you need some help running things locally?

Also, how about let's just get five in at a time. The more you add, the more everything has to be right first.

2024-07-13 19:02 UTC, maserion commented
> Do you need some help running things locally?
> 
> Also, how about let's just get five in at a time. The more you add, the more everything has to be right first.

the issue is with one test, all other looks fine

2024-07-14 16:48 UTC, kberg commented on src/server/cards/prelude2/MicrogravityNutrition.ts
> +  public override bespokePlay(player: IPlayer) {
Yeah, it should change there too. (NB, custom code like that makes the card incompatible with the Engineer milestone.) It should be OK.

2024-07-14 17:06 UTC, kberg requested changes
The changes to package.json and package-lock.json have to go before merge.

Still needs 3 more tests. As I was suggesting earlier, perhaps remove the 3 new cards to a new PR.

2024-07-14 17:06 UTC, kberg commented on src/server/cards/prelude2/UnexpectedApplication.ts
> +  public override bespokePlay(player: IPlayer) {
This is a little bit out of order because the card has to be played before raising Venus 1 step.

But doing that makes the whole thing more complicated: code has to identify if Reds are in power (using the canAfford behavior.) Let's address this by adding custom spend behavior, so the card looks like this:

```
behavior: {
  spend: {cards: 1},
  global: {venus: 1},
```

Don't do that, I'll do it. For now, this will do.

2024-07-16 13:16 UTC, kberg approved these changes
Looks great. Thank you!

2024-07-16 13:17 UTC, merged